version: "3.9"

services:
  ai:
    build: ./ai_service
    container_name: ai-service
    ports:
      - "8000:8000"
    restart: unless-stopped

  nextapp:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AI_URL=http://ai:8000   # Next.js podr√° usar esta variable si quieres
    depends_on:
      - ai
    restart: unless-stopped
